name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install 🔧
        run: yarn

      - name: Run Test 🔨
        run: yarn run lint

      - name: Build 👷
        run: yarn run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.KEY }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
